setono_sylius_variant_link_shop_product_variant_show:
    path: /products/{slug}/{variant_identifier}
    methods: [GET]
    defaults:
        _controller: setono_sylius_variant_link.controller.action.show_product_variant
        _sylius:
            template: "@SyliusShop/Product/show.html.twig"
            repository:
                method: findOneByChannelAndSlug
                arguments:
                    - "expr:service('sylius.context.channel').getChannel()"
                    - "expr:service('sylius.context.locale').getLocaleCode()"
                    - $slug
